- name: Build and install Neovim stable
  hosts: localhost
  tasks:
    - name: Install build prerequisites
      become: true
      apt:
        pkg:
          - ninja-build
          - gettext
          - cmake
          - unzip
          - curl
          - make
    - name: Clone neovim repository
      git:
        repo: "git@github.com:neovim/neovim.git"
        dest: "{{ lookup('env', 'HOME')/neovim }}"
        version: stable
        accept_hostkey: yes
    - name: Build release
      shell: "cd ~/neovim && make CMAKE_BUILD_TYPE=Release"
    - name: Install built neovim package
      become: true
      shell: "cd build && cpack -G DEB && dpkg -i nvim-linux64.deb"

